### ISSUE TITLE
"Nethered" overworld when moving from nether to overworld

### ISSUE THREAD

**Issue by Arlyss** [Multiverse/Multiverse-NetherPortals#125]
I'm encoutering a weird problem on my server :

**Description :**

When i move from overworld to nether, all is right,
but when i go back to overworld, i return to a "nethered" overworld :

- water disappeared,
- many blocks are replaced by others (or invisible, like foliage)
- sky is red (like nether)
- i hear nether sounds
- ...

If i disconnect and reconnect to the server, all is right,
i'm in a normal overworld, at the same position.
It seems that the portal return is done to a "corrupted instance of overworld".

**Context :**

My objective was to have a bukkit/forge server.
So i used kCauldron, including bukkit plugins and forge mods.
All is working fine except this nether's portals bug.

I'm completly conscient that my context is "special",
but i would appreciate some ideas to resolve the problem...

**Configuration tests :**

[tests.txt](https://github.com/Multiverse/Multiverse-NetherPortals/files/949010/tests.txt) for scite/notepad++
[tests_notepad.txt](https://github.com/Multiverse/Multiverse-NetherPortals/files/949011/tests_notepad.txt) for windows notepad

**Comment by Jadiction** [comment]
I don't believe this is an issue in Multiverse. Closing issue because it's an old post. If you are still running a Minecraft server and this persists, try updating all the Multiverse plugins and try again, otherwise please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.
