### ISSUE TITLE
Mobs not moving through Nether Portals

### ISSUE THREAD

**Issue by rpvernon** [Multiverse/Multiverse-NetherPortals#72]
When I push a mob through a nether portal, it disappears, but does not appear in the world on the other side.

**Comment by Matti-Koopa** [comment]
I am having this issue as well. Is this fix not included in the newest version or did it break again?

**Comment by ac9607** [comment]
Waester's fix is working. Can anyone merge the fix into master branch?

**Comment by csorrows** [comment]
I have verified this issue effects mobs and items. I'm using a world and it's normal _nether and this is occurring. Prior to using multiverse, this issue did not occur in the same set of worlds. This does not seem to me a server issue.

**Comment by dali99** [comment]
Can Confirm as well using 2.5-b691

**Comment by groovybluedog** [comment]
Weaster's fix sounds great, but all of the downloads aren't .jar files. I have no programming knowledge outside of web design. How may I add those fixes to my current jar or download a jar with those fixes in? Any help appreciated, as I am desperate to fix this.

**Comment by Amanoo** [comment]
I can't even find this Waester or his fix. And I'm definitely having problems with this.

**Comment by pmdevita** [comment]
Any progress on this? As far as I can tell this is still a problem in the recent builds

**Comment by Castiella** [comment]
all these issues being referenced since 2016 - guessing there is a command/config fix for this?

**Comment by F4Fridey** [comment]
So when will this be fixed?

**Comment by benwoo1110** [comment]
Apparently after all these years, this issue still has not been fixed...

**Comment by K4ds3** [comment]
Would be awesome if this would get fixed someday :(

**Comment by nicegamer7** [comment]
I'll take a look at this soon.

**Comment by pmdevita** [comment]
https://github.com/Multiverse/Multiverse-NetherPortals/blob/465f60763b88820bdd45c385e9e854ac6676702d/src/main/java/com/onarandombox/MultiverseNetherPortals/listeners/MVNPEntityListener.java#L91

It appears that only player teleporting has been implemented and all other entities are blocked out of safety. One could probably refactor the function to teleport the player to also allow other entities through. It appears the plugin has to re-implement a lot of portal functionality so it would be best to try and use the same code as for the player.

**Comment by nicegamer7** [comment]
Thanks @pmdevita. Originally, I thought the same thing. But that turned out not to be the issue, see #156 for what was wrong.

**Comment by Nase00** [comment]
I was able to get entity travel partially working using the build from https://github.com/Multiverse/Multiverse-NetherPortals/pull/156#issuecomment-641366973. (Thank you for that, btw, it's certainly better than it not working at all!)

Here's the issue I'm still experiencing with my `NORMAL` and `NETHER` multiverse worlds that are both linked to each other: if an origin portal is created in one dimension in close enough proximity that it pairs with an existing player-created destination portal, entities are unable to use the destination portal to travel back out to any linked portal. (Tested several times using fresh spawn eggs in creative.) Not at all familiar with nether portal code, but I'm guessing it may have to do with some missing tags/config that only gets created when one of the portals is "force spawned."

Here's the specific scenario in which it seems to work consistently:
In one dimension, create an origin portal in an area where stepping through it forces the generation of a brand new destination portal in the destination dimension. (I.e., there can't be any active portals in the destination dimension close enough for it to link to. It _has_ to "force spawn" a new portal.) This seems to allow mobs to travel from either end portal to the other.

For example, to move mobs from the overworld into the nether and back out into another location in the overworld, 2 pairs of portals must be used, and both must have their other-dimensional-counterparts freshly generated from the player stepping through them. This makes it tricky to link 2 established locations, because at least 2 of the portals linking the locations together will end up in random spots. (A small workaround I found is that players can sort of control the height at which portals spawn in, by destroying a naturally generated destination portal, filling in the blocks it spawned in, `/mvtp`'ing back to the origin portal, and traveling through it to re-generate the destination portal at the next highest available empty block space.)

`/version` reports `This server is running CraftBukkit version git-Spigot-b5a13e6-927200a (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)`

Running these mods:
```
NoSpawnChunks.jar
LuckPerms-Bukkit-5.1.98.jar
CustomTime-2.0.jar
Multiverse-Core-4.1.0.jar
Slack.jar
Dynmap-3.1-beta-3a-spigot.jar
dynmap-structures-2.3.0-all.jar 
Multiverse-Inventories-3.0.0.jar
worldedit-bukkit-7.0.1.jar
Multiverse-NetherPortals-4.1.1.jar
worldguard-bukkit-7.0.0.jar
Multiverse-Portals-4.0.0.jar
```
